### ISSUE TITLE
[Feature] 유저 생성, 유저 정보 조회 기능 구현

### ISSUE THREAD

**Issue by junseoplee** [Someup/backend#15]
## 📑 작업 사항
- 카카오 로그인 후 토큰으로 부터 유저 정보 추출 및 생성
- 유저 정보를 조회할 수 있는 API 구현
- User 엔티티에 프로필 이미지 url 필드 추가

## To-do
- [x] 카카오 로그인 기능 추가 리팩토링
- [x] 유저 생성 메서드 로직 수정
- [x] 프로필 이미지 필드 추가 및 구현
- [x] 유저 정보 조회 API 구현
