### ISSUE TITLE
[Refactor] API Request 리팩토링 및 코드 컨벤션

### ISSUE THREAD

**Issue by junseoplee** [Someup/backend#18]
## 📑 작업 사항
API Request 리팩토링 및 전체적인 코드 컨벤션

## To-do
- [x] API Request 리팩토링
- [x] 의존성 변경
- [x] API URI 변경
- [x] 코드 컨벤션 맞춤
