### ISSUE TITLE
[Refactor] 토큰, 리이슈, 로그아웃 로직 변경

### ISSUE THREAD

**Issue by junseoplee** [Someup/backend#29]
## 📑 작업 사항
레디스 리프레시 토큰 저장, 조회 방식 변경
로그아웃 로직 변경

## To-do
- [x] 레디스 저장 방식 변경
- [x] 레디스 조회 방식 변경
- [x] 로그아웃 로직 변경
