### ISSUE TITLE
[Feature] 요약글 아카이빙을 위한 Entity 생성

### ISSUE THREAD

**Issue by yongbin97** [Someup/backend#4]
## 📑 작업 사항
기본적인 Post, Memo, Tag와 관련된 Entity를 생성합니다.
Domain 중심 디렉토리 구조로 수정

## To-do
- [x] 디렉토리 구조 수정
- [x] Post Entity 생성
- [x] Memo Entity 생성
- [x] Tag Entity 생성
