### ISSUE TITLE
[Feature] 게시글 관련 API 수정사항

### ISSUE THREAD

**Issue by yongbin97** [Someup/backend#41]
## 📑 작업 사항
게시글 관련 API 아카이브 적용
AI 요약 시 제목 받아오기

## To-do
- [x] 게시글 수정 시 아카이브 추가하기
- [x] 게시글 목록 조회 아카이브 조건 추가
- [x] AI 요약 시 title 받아오기
- [x] AI 요약 시 출처 제거
- [x] Post 관련 API 리팩토링

## ETC
기타 사항을 작성해 주세요.
